#include "platform/wayland/WaylandBackend.hxx"

#include <dirent.h>
#include <fcntl.h>
#include <linux/joystick.h>
#include <poll.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <unistd.h>
#include <wayland-client-protocol.h>

////////////////////////////////////////////////////////////////////////////////////////
/// NOLINTBEGIN(readability-identifier-naming)

/* Generated by wayland-scanner 1.25.0 */

/*
 * Copyright © 2014      Jonas Ådahl
 * Copyright © 2015      Red Hat Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

// #include <stdbool.h>
// #include <stdint.h>
// #include <stdlib.h>
//
// #include "wayland-util.h"

#ifndef __has_attribute
#define __has_attribute(x) 0 /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
// #define WL_PRIVATE __attribute__((visibility("hidden")))
#define WL_PRIVATE
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_pointer_interface;
extern const struct wl_interface wl_region_interface;
extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface zwp_confined_pointer_v1_interface;
extern const struct wl_interface zwp_locked_pointer_v1_interface;

static const struct wl_interface* pointer_constraints_unstable_v1_types[] = {
    NULL,
    NULL,
    &zwp_locked_pointer_v1_interface,
    &wl_surface_interface,
    &wl_pointer_interface,
    &wl_region_interface,
    NULL,
    &zwp_confined_pointer_v1_interface,
    &wl_surface_interface,
    &wl_pointer_interface,
    &wl_region_interface,
    NULL,
    &wl_region_interface,
    &wl_region_interface,
};

static const struct wl_message zwp_pointer_constraints_v1_requests[] = {
    {"destroy", "", pointer_constraints_unstable_v1_types + 0},
    {"lock_pointer", "noo?ou", pointer_constraints_unstable_v1_types + 2},
    {"confine_pointer", "noo?ou", pointer_constraints_unstable_v1_types + 7},
};

WL_PRIVATE const struct wl_interface zwp_pointer_constraints_v1_interface = {
    "zwp_pointer_constraints_v1",        1, 3,
    zwp_pointer_constraints_v1_requests, 0, NULL,
};

static const struct wl_message zwp_locked_pointer_v1_requests[] = {
    {"destroy", "", pointer_constraints_unstable_v1_types + 0},
    {"set_cursor_position_hint", "ff",
     pointer_constraints_unstable_v1_types + 0},
    {"set_region", "?o", pointer_constraints_unstable_v1_types + 12},
};

static const struct wl_message zwp_locked_pointer_v1_events[] = {
    {"locked", "", pointer_constraints_unstable_v1_types + 0},
    {"unlocked", "", pointer_constraints_unstable_v1_types + 0},
};

WL_PRIVATE const struct wl_interface zwp_locked_pointer_v1_interface = {
    "zwp_locked_pointer_v1",        1, 3,
    zwp_locked_pointer_v1_requests, 2, zwp_locked_pointer_v1_events,
};

static const struct wl_message zwp_confined_pointer_v1_requests[] = {
    {"destroy", "", pointer_constraints_unstable_v1_types + 0},
    {"set_region", "?o", pointer_constraints_unstable_v1_types + 13},
};

static const struct wl_message zwp_confined_pointer_v1_events[] = {
    {"confined", "", pointer_constraints_unstable_v1_types + 0},
    {"unconfined", "", pointer_constraints_unstable_v1_types + 0},
};

WL_PRIVATE const struct wl_interface zwp_confined_pointer_v1_interface = {
    "zwp_confined_pointer_v1",        1, 2,
    zwp_confined_pointer_v1_requests, 2, zwp_confined_pointer_v1_events,
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////

/* Generated by wayland-scanner 1.25.0 */

/*
 * Copyright © 2014      Jonas Ådahl
 * Copyright © 2015      Red Hat Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

// #include <stdbool.h>
// #include <stdint.h>
// #include <stdlib.h>
//
// #include "wayland-util.h"
//
// #ifndef __has_attribute
// #define __has_attribute(x) 0 /* Compatibility with non-clang compilers. */
// #endif
//
// #if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
// #define WL_PRIVATE __attribute__((visibility("hidden")))
// #else
// #define WL_PRIVATE
// #endif

extern const struct wl_interface wl_pointer_interface;
extern const struct wl_interface zwp_relative_pointer_v1_interface;

static const struct wl_interface* relative_pointer_unstable_v1_types[] = {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &zwp_relative_pointer_v1_interface,
    &wl_pointer_interface,
};

static const struct wl_message zwp_relative_pointer_manager_v1_requests[] = {
    {"destroy", "", relative_pointer_unstable_v1_types + 0},
    {"get_relative_pointer", "no", relative_pointer_unstable_v1_types + 6},
};

WL_PRIVATE const struct wl_interface zwp_relative_pointer_manager_v1_interface =
    {
        "zwp_relative_pointer_manager_v1",        1, 2,
        zwp_relative_pointer_manager_v1_requests, 0, NULL,
};

static const struct wl_message zwp_relative_pointer_v1_requests[] = {
    {"destroy", "", relative_pointer_unstable_v1_types + 0},
};

static const struct wl_message zwp_relative_pointer_v1_events[] = {
    {"relative_motion", "uuffff", relative_pointer_unstable_v1_types + 0},
};

WL_PRIVATE const struct wl_interface zwp_relative_pointer_v1_interface = {
    "zwp_relative_pointer_v1",        1, 1,
    zwp_relative_pointer_v1_requests, 1, zwp_relative_pointer_v1_events,
};

////////////////////////////////////////////////////////////////////////////////////////////

/* Generated by wayland-scanner 1.25.0 */

/*
 * Copyright © 2018 Simon Ser
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

// #include <stdbool.h>
// #include <stdint.h>
// #include <stdlib.h>
//
// #include "wayland-util.h"
//
// #ifndef __has_attribute
// #define __has_attribute(x) 0 /* Compatibility with non-clang compilers. */
// #endif
//
// #if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
// #define WL_PRIVATE __attribute__((visibility("hidden")))
// #else
// #define WL_PRIVATE
// #endif

extern const struct wl_interface xdg_toplevel_interface;
extern const struct wl_interface zxdg_toplevel_decoration_v1_interface;

static const struct wl_interface* xdg_decoration_unstable_v1_types[] = {
    NULL,
    &zxdg_toplevel_decoration_v1_interface,
    &xdg_toplevel_interface,
};

static const struct wl_message zxdg_decoration_manager_v1_requests[] = {
    {"destroy", "", xdg_decoration_unstable_v1_types + 0},
    {"get_toplevel_decoration", "no", xdg_decoration_unstable_v1_types + 1},
};

WL_PRIVATE const struct wl_interface zxdg_decoration_manager_v1_interface = {
    "zxdg_decoration_manager_v1",        2, 2,
    zxdg_decoration_manager_v1_requests, 0, NULL,
};

static const struct wl_message zxdg_toplevel_decoration_v1_requests[] = {
    {"destroy", "", xdg_decoration_unstable_v1_types + 0},
    {"set_mode", "u", xdg_decoration_unstable_v1_types + 0},
    {"unset_mode", "", xdg_decoration_unstable_v1_types + 0},
};

static const struct wl_message zxdg_toplevel_decoration_v1_events[] = {
    {"configure", "u", xdg_decoration_unstable_v1_types + 0},
};

WL_PRIVATE const struct wl_interface zxdg_toplevel_decoration_v1_interface = {
    "zxdg_toplevel_decoration_v1",        2, 3,
    zxdg_toplevel_decoration_v1_requests, 1, zxdg_toplevel_decoration_v1_events,
};

///////////////////////////////////////////////////////////////////////////////////////////

/* Generated by wayland-scanner 1.25.0 */

/*
 * Copyright © 2017 Red Hat Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

// #include <stdbool.h>
// #include <stdint.h>
// #include <stdlib.h>
//
// #include "wayland-util.h"
//
// #ifndef __has_attribute
// #define __has_attribute(x) 0 /* Compatibility with non-clang compilers. */
// #endif
//
// #if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
// #define WL_PRIVATE __attribute__((visibility("hidden")))
// #else
// #define WL_PRIVATE
// #endif

extern const struct wl_interface wl_output_interface;
extern const struct wl_interface zxdg_output_v1_interface;

static const struct wl_interface* xdg_output_unstable_v1_types[] = {
    NULL,
    NULL,
    &zxdg_output_v1_interface,
    &wl_output_interface,
};

static const struct wl_message zxdg_output_manager_v1_requests[] = {
    {"destroy", "", xdg_output_unstable_v1_types + 0},
    {"get_xdg_output", "no", xdg_output_unstable_v1_types + 2},
};

WL_PRIVATE const struct wl_interface zxdg_output_manager_v1_interface = {
    "zxdg_output_manager_v1", 3, 2, zxdg_output_manager_v1_requests, 0, NULL,
};

static const struct wl_message zxdg_output_v1_requests[] = {
    {"destroy", "", xdg_output_unstable_v1_types + 0},
};

static const struct wl_message zxdg_output_v1_events[] = {
    {"logical_position", "ii", xdg_output_unstable_v1_types + 0},
    {"logical_size", "ii", xdg_output_unstable_v1_types + 0},
    {"done", "", xdg_output_unstable_v1_types + 0},
    {"name", "2s", xdg_output_unstable_v1_types + 0},
    {"description", "2s", xdg_output_unstable_v1_types + 0},
};

WL_PRIVATE const struct wl_interface zxdg_output_v1_interface = {
    "zxdg_output_v1", 3, 1, zxdg_output_v1_requests, 5, zxdg_output_v1_events,
};

//////////////////////////////////////////////////////////////////////////////////////////////

/* Generated by wayland-scanner 1.25.0 */

/*
 * Copyright © 2008-2013 Kristian Høgsberg
 * Copyright © 2013      Rafael Antognolli
 * Copyright © 2013      Jasper St. Pierre
 * Copyright © 2010-2013 Intel Corporation
 * Copyright © 2015-2017 Samsung Electronics Co., Ltd
 * Copyright © 2015-2017 Red Hat Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

// #include <stdbool.h>
// #include <stdint.h>
// #include <stdlib.h>
//
// #include "wayland-util.h"
//
// #ifndef __has_attribute
// #define __has_attribute(x) 0 /* Compatibility with non-clang compilers. */
// #endif
//
// #if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
// #define WL_PRIVATE __attribute__((visibility("hidden")))
// #else
// #define WL_PRIVATE
// #endif

extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_seat_interface;
extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface xdg_popup_interface;
extern const struct wl_interface xdg_positioner_interface;
extern const struct wl_interface xdg_surface_interface;
extern const struct wl_interface xdg_toplevel_interface;

static const struct wl_interface* xdg_shell_types[] = {
    NULL,
    NULL,
    NULL,
    NULL,
    &xdg_positioner_interface,
    &xdg_surface_interface,
    &wl_surface_interface,
    &xdg_toplevel_interface,
    &xdg_popup_interface,
    &xdg_surface_interface,
    &xdg_positioner_interface,
    &xdg_toplevel_interface,
    &wl_seat_interface,
    NULL,
    NULL,
    NULL,
    &wl_seat_interface,
    NULL,
    &wl_seat_interface,
    NULL,
    NULL,
    &wl_output_interface,
    &wl_seat_interface,
    NULL,
    &xdg_positioner_interface,
    NULL,
};

static const struct wl_message xdg_wm_base_requests[] = {
    {"destroy", "", xdg_shell_types + 0},
    {"create_positioner", "n", xdg_shell_types + 4},
    {"get_xdg_surface", "no", xdg_shell_types + 5},
    {"pong", "u", xdg_shell_types + 0},
};

static const struct wl_message xdg_wm_base_events[] = {
    {"ping", "u", xdg_shell_types + 0},
};

WL_PRIVATE const struct wl_interface xdg_wm_base_interface = {
    "xdg_wm_base", 7, 4, xdg_wm_base_requests, 1, xdg_wm_base_events,
};

static const struct wl_message xdg_positioner_requests[] = {
    {"destroy", "", xdg_shell_types + 0},
    {"set_size", "ii", xdg_shell_types + 0},
    {"set_anchor_rect", "iiii", xdg_shell_types + 0},
    {"set_anchor", "u", xdg_shell_types + 0},
    {"set_gravity", "u", xdg_shell_types + 0},
    {"set_constraint_adjustment", "u", xdg_shell_types + 0},
    {"set_offset", "ii", xdg_shell_types + 0},
    {"set_reactive", "3", xdg_shell_types + 0},
    {"set_parent_size", "3ii", xdg_shell_types + 0},
    {"set_parent_configure", "3u", xdg_shell_types + 0},
};

WL_PRIVATE const struct wl_interface xdg_positioner_interface = {
    "xdg_positioner", 7, 10, xdg_positioner_requests, 0, NULL,
};

static const struct wl_message xdg_surface_requests[] = {
    {"destroy", "", xdg_shell_types + 0},
    {"get_toplevel", "n", xdg_shell_types + 7},
    {"get_popup", "n?oo", xdg_shell_types + 8},
    {"set_window_geometry", "iiii", xdg_shell_types + 0},
    {"ack_configure", "u", xdg_shell_types + 0},
};

static const struct wl_message xdg_surface_events[] = {
    {"configure", "u", xdg_shell_types + 0},
};

WL_PRIVATE const struct wl_interface xdg_surface_interface = {
    "xdg_surface", 7, 5, xdg_surface_requests, 1, xdg_surface_events,
};

static const struct wl_message xdg_toplevel_requests[] = {
    {"destroy", "", xdg_shell_types + 0},
    {"set_parent", "?o", xdg_shell_types + 11},
    {"set_title", "s", xdg_shell_types + 0},
    {"set_app_id", "s", xdg_shell_types + 0},
    {"show_window_menu", "ouii", xdg_shell_types + 12},
    {"move", "ou", xdg_shell_types + 16},
    {"resize", "ouu", xdg_shell_types + 18},
    {"set_max_size", "ii", xdg_shell_types + 0},
    {"set_min_size", "ii", xdg_shell_types + 0},
    {"set_maximized", "", xdg_shell_types + 0},
    {"unset_maximized", "", xdg_shell_types + 0},
    {"set_fullscreen", "?o", xdg_shell_types + 21},
    {"unset_fullscreen", "", xdg_shell_types + 0},
    {"set_minimized", "", xdg_shell_types + 0},
};

static const struct wl_message xdg_toplevel_events[] = {
    {"configure", "iia", xdg_shell_types + 0},
    {"close", "", xdg_shell_types + 0},
    {"configure_bounds", "4ii", xdg_shell_types + 0},
    {"wm_capabilities", "5a", xdg_shell_types + 0},
};

WL_PRIVATE const struct wl_interface xdg_toplevel_interface = {
    "xdg_toplevel", 7, 14, xdg_toplevel_requests, 4, xdg_toplevel_events,
};

static const struct wl_message xdg_popup_requests[] = {
    {"destroy", "", xdg_shell_types + 0},
    {"grab", "ou", xdg_shell_types + 22},
    {"reposition", "3ou", xdg_shell_types + 24},
};

static const struct wl_message xdg_popup_events[] = {
    {"configure", "iiii", xdg_shell_types + 0},
    {"popup_done", "", xdg_shell_types + 0},
    {"repositioned", "3u", xdg_shell_types + 0},
};

WL_PRIVATE const struct wl_interface xdg_popup_interface = {
    "xdg_popup", 7, 3, xdg_popup_requests, 3, xdg_popup_events,
};

/// NOLINTEND(readability-identifier-naming)
/////////////////////////////////////////////////////////////////////////////////////////////////

static void seatHandleCapabilities(void* data, wl_seat* seat,
                                   uint32_t capabilities) {
    auto* ctx = static_cast<WaylandContext*>(data);

    if ((capabilities & WL_SEAT_CAPABILITY_POINTER) && !ctx->pointer) {
        ctx->pointer = wl_seat_get_pointer(seat);
        addListenerToPointer(*ctx, ctx->pointer);
    } else if (!(capabilities & WL_SEAT_CAPABILITY_POINTER) && ctx->pointer) {
        wl_pointer_release(ctx->pointer);
        ctx->pointer = nullptr;
    }

    if ((capabilities & WL_SEAT_CAPABILITY_KEYBOARD) && !ctx->keyboard) {
        ctx->keyboard = wl_seat_get_keyboard(seat);
        addListenerToKeyboard(*ctx, ctx->keyboard);
    } else if (!(capabilities & WL_SEAT_CAPABILITY_KEYBOARD) && ctx->keyboard) {
        wl_keyboard_release(ctx->keyboard);
        ctx->keyboard = nullptr;
    }
}

static void seatHandleName(void* data, wl_seat* seat, const char* name) {
    (void)data;
    (void)seat;
    (void)name;
    // #ifdef DEBUG
    //     std::cout << "[Wayland] Active seat group identified: " << name <<
    //     "\n";
    // #endif
}

static void wmBaseHandlePing(void* data, xdg_wm_base* wmBase, uint32_t serial) {
    (void)data;
    xdg_wm_base_pong(wmBase, serial);
}

static const wl_seat_listener KSEAT_LISTENER = {
    .capabilities = seatHandleCapabilities, .name = seatHandleName};

static const xdg_wm_base_listener KWM_BASE_LISTENER = {.ping =
                                                           wmBaseHandlePing};

static void registryHandleGlobal(void* data, wl_registry* registry,
                                 uint32_t name, const char* interface,
                                 uint32_t version) {
    auto* ctx = static_cast<WaylandContext*>(data);

    if (std::strcmp(interface, "wl_compositor") == 0) {
        ctx->compositor = static_cast<wl_compositor*>(wl_registry_bind(
            registry, name, &wl_compositor_interface, std::min(version, 4u)));
    } else if (std::strcmp(interface, "wl_shm") == 0) {
        ctx->shm = static_cast<wl_shm*>(
            wl_registry_bind(registry, name, &wl_shm_interface, 1));
    } else if (std::strcmp(interface, "wl_seat") == 0) {
        ctx->seat = static_cast<wl_seat*>(wl_registry_bind(
            registry, name, &wl_seat_interface, std::min(version, 7u)));
        wl_seat_add_listener(ctx->seat, &KSEAT_LISTENER, ctx);
    } else if (std::strcmp(interface, "xdg_wm_base") == 0) {
        ctx->wmBase = static_cast<xdg_wm_base*>(
            wl_registry_bind(registry, name, &xdg_wm_base_interface, 1));

        xdg_wm_base_add_listener(ctx->wmBase, &KWM_BASE_LISTENER, nullptr);
    } else if (std::strcmp(interface, "wp_pointer_constraints_v1") == 0) {
        ctx->pointerConstraints =
            static_cast<zwp_pointer_constraints_v1*>(wl_registry_bind(
                registry, name, &zwp_pointer_constraints_v1_interface, 1));
    } else if (std::strcmp(interface, "zwp_relative_pointer_manager_v1") == 0) {
        ctx->relativePointerManager =
            static_cast<zwp_relative_pointer_manager_v1*>(wl_registry_bind(
                registry, name, &zwp_relative_pointer_manager_v1_interface, 1));
    }

    if (std::strcmp(interface, wl_seat_interface.name) == 0) {
        ctx->seat = static_cast<wl_seat*>(wl_registry_bind(
            registry, name, &wl_seat_interface, /*version=*/7));
    } else if (std::strcmp(interface, wl_data_device_manager_interface.name) ==
               0) {
        ctx->dataDeviceManager = static_cast<wl_data_device_manager*>(
            wl_registry_bind(registry, name, &wl_data_device_manager_interface,
                             /*version=*/3));
    }

    if (ctx->dataDeviceManager && ctx->seat && !ctx->dataDevice) {
        ctx->dataDevice = wl_data_device_manager_get_data_device(
            ctx->dataDeviceManager, ctx->seat);
    }
}

static void registryHandleGlobalRemove(void* data, wl_registry* registry,
                                       uint32_t name) {
    (void)data;
    (void)registry;
    (void)name;
}

static const wl_registry_listener KREGISTRY_LISTENER = {
    .global = registryHandleGlobal,
    .global_remove = registryHandleGlobalRemove};

WaylandBackend::~WaylandBackend() {
    if (m_ctx.cursorTheme) {
        wl_cursor_theme_destroy(m_ctx.cursorTheme);
        m_ctx.cursorTheme = nullptr;
    }

    shutdown();
}

bool WaylandBackend::initialize(const VeraAppInfo& info) {
    (void)info;

    m_ctx.display = wl_display_connect(nullptr);
    if (!m_ctx.display) {
        return false;
    }

    m_ctx.registry = wl_display_get_registry(m_ctx.display);
    wl_registry_add_listener(m_ctx.registry, &KREGISTRY_LISTENER, &m_ctx);

    wl_display_roundtrip(m_ctx.display);

    if (!m_ctx.compositor || !m_ctx.wmBase) {
        printf("[Wayland] Essential shell interfaces missing.\n");
        shutdown();
        return false;
    }

    initializeThemeWayland(m_ctx);
    initializeJoystickWayland(m_ctx);

    return true;
}

void WaylandBackend::shutdown() {
    shutdownJoystickWayland(m_ctx);
    shutdownThemeWayland();
    unlockPointerWayland(m_ctx);

    if (m_ctx.wmBase) {
        xdg_wm_base_destroy(m_ctx.wmBase);
        m_ctx.wmBase = nullptr;
    }
    if (m_ctx.compositor) {
        wl_compositor_destroy(m_ctx.compositor);
        m_ctx.compositor = nullptr;
    }
    if (m_ctx.shm) {
        wl_shm_destroy(m_ctx.shm);
        m_ctx.shm = nullptr;
    }
    if (m_ctx.seat) {
        wl_seat_destroy(m_ctx.seat);
        m_ctx.seat = nullptr;
    }
    if (m_ctx.pointerConstraints) {
        zwp_pointer_constraints_v1_destroy(m_ctx.pointerConstraints);
        m_ctx.pointerConstraints = nullptr;
    }
    if (m_ctx.relativePointerManager) {
        zwp_relative_pointer_manager_v1_destroy(m_ctx.relativePointerManager);
        m_ctx.relativePointerManager = nullptr;
    }
    if (m_ctx.registry) {
        wl_registry_destroy(m_ctx.registry);
        m_ctx.registry = nullptr;
    }
    if (m_ctx.display) {
        wl_display_disconnect(m_ctx.display);
        m_ctx.display = nullptr;
    }
}

nostd::Expected<nostd::UniquePtr<VeraWindow>, VeraError>
WaylandBackend::createWindow(const VeraWindowInfo& info) {
    VeraWindowHandle handle =
        static_cast<VeraWindowHandle>(m_ctx.allocateHandle());

    try {
        auto window = nostd::makeUnique<WaylandWindow>(m_ctx, handle, info);
        return nostd::UniquePtr<VeraWindow>(window.release());
    } catch (const std::exception& e) {
        return nostd::Unexpected(VeraError{VeraErrorType::WindowCreationFailed,
                                           "Failed to create Wayland window"});
    }
}

void WaylandBackend::pollEvents() {
    updateJoystickWayland(m_ctx);
    updateThemeWayland();

    pollEventsWayland(m_ctx, m_quitRequestCallback, m_displayChangeCallback);

    size_t i = 0;
    while (i < m_ctx.windowCount) {
        WaylandWindow* window = m_ctx.windowsBySurface[i].window;

        if (window && window->isPendingDeletion()) {
            delete window;

            m_ctx.windowsBySurface[i] =
                m_ctx.windowsBySurface[m_ctx.windowCount - 1];
            m_ctx.windowsBySurface[--m_ctx.windowCount] = {};
        } else {
            ++i;
        }
    }

    if (m_ctx.display) {
        wl_display_flush(m_ctx.display);
    }
}

void WaylandBackend::waitEvents() {
    updateJoystickWayland(m_ctx);
    updateThemeWayland();
    waitForEventsWayland(m_ctx, m_quitRequestCallback, m_displayChangeCallback);
}

void WaylandBackend::waitEventsTimeout(double timeoutSeconds) {
    updateJoystickWayland(m_ctx);
    updateThemeWayland();
    waitForEventsWithTimeoutWayland(
        m_ctx, timeoutSeconds, m_quitRequestCallback, m_displayChangeCallback);
}

void WaylandBackend::setQuitRequestCallback(nostd::Function<bool()> callback) {
    m_quitRequestCallback = callback;
}

void WaylandBackend::setDisplayChangeCallback(
    nostd::Function<void()> callback) {
    m_displayChangeCallback = callback;
}

void WaylandBackend::setSystemThemeChangeCallback(
    nostd::Function<void(VeraSystemTheme)> callback) {
    m_systemThemeChangeCallback = callback;
}

nostd::Vector<VeraMonitorInfo> WaylandBackend::getMonitors() const {
    return getMonitorsWayland(m_ctx);
}

VeraMonitorInfo WaylandBackend::getPrimaryMonitor() const {
    return getPrimaryMonitorWayland(m_ctx);
}

VeraMonitorInfo WaylandBackend::getMonitorAt(int32_t x, int32_t y) const {
    return getMonitorAtCoordinateXYWayland(m_ctx, x, y);
}

nostd::Vector<VeraDisplayModeInfo> WaylandBackend::getSupportedDisplayModes(
    const VeraMonitorInfo& monitor) const {
    return getSupportedDisplayModesWayland(m_ctx, monitor);
}

bool WaylandBackend::supportsNativeDecorationHitTesting() const { return true; }

VeraStringView WaylandBackend::getClipboardText() const {
    return getClipboardTextWayland(m_ctx);
}

void WaylandBackend::setClipboardText(const char* text) {
    setClipboardTextWayland(m_ctx, text);
}

bool WaylandBackend::hasClipboardText() const {
    return hasClipboardTextWayland(m_ctx);
}

void WaylandBackend::setDragCallback(VeraDragCallback callback) {
    setDragCallbackWayland(m_ctx, callback);
}

VeraSystemTheme WaylandBackend::getSystemTheme() const {
    return (getActiveThemeModeWayland() == VeraThemeMode::Dark)
               ? VeraSystemTheme::Dark
               : VeraSystemTheme::Light;
}

nostd::Vector<VeraInputDeviceInfo> WaylandBackend::getInputDevices() const {
    return {};
}

VeraNativeHandle WaylandBackend::getNativeHandle() const {
    VeraNativeHandle handle{};
    handle.display = m_ctx.display;
    return handle;
}

void WaylandBackend::applySettings(const VeraSettings& settings) {
    m_ctx.keyRepeatDelay = settings.keyRepeatSettings.delayMs;
    m_ctx.keyRepeatRate = settings.keyRepeatSettings.rate;
}

void WaylandBackend::setCursorShape(VeraCursorShape cursh) {
    setCursorShapeWayland(m_ctx, cursh);
}

/////////////////////////////////////////////////////////

static VeraCursorMode sCurrentMode = VeraCursorMode::Normal;

// void advanceCursorFrame(WaylandContext& ctx) {
//     if (!ctx.currentCursor || ctx.currentCursor->image_count <= 1 ||
//     !ctx.pointer) {
//         return;
//     }
//
//     // Move to the next frame, looping back to 0 at the end
//     ctx.currentFrameIndex = (ctx.currentFrameIndex + 1) %
//     ctx.currentCursor->image_count;
//
//     wl_cursor_image* image =
//     ctx.currentCursor->images[ctx.currentFrameIndex]; wl_buffer* buffer =
//     wl_cursor_image_get_buffer(image);
//
//     // Attach the new frame's buffer
//     wl_surface_attach(ctx.cursorSurface, buffer, 0, 0);
//     wl_surface_damage(ctx.cursorSurface, 0, 0, image->width, image->height);
//     wl_surface_commit(ctx.cursorSurface);
//
//     // Note: The serial is only strictly required on .enter or .button.
//     // Frame updates during an active session can use the last cached
//     pointerSerial. wl_pointer_set_cursor(ctx.pointer, ctx.pointerSerial,
//     ctx.cursorSurface,
//                           image->hotspot_x, image->hotspot_y);
//
//     // Schedule the next frame using the cursor's native millisecond delay
//     uint32_t delayMs = image->delay;
//
//     // TODO: Trigger your engine's timer callback here to run
//     // advanceCursorFrame(ctx) again after 'delayMs' milliseconds.
// }

// 2. The structural logic that commits directly to the compositor
void applyCursorToWayland(WaylandContext& ctx, uint32_t serial) {
    if (!ctx.pointer) return;

    const char* cursorName = "left_ptr";
    switch (ctx.pendingShape) {
        case VeraCursorShape::Arrow:
            cursorName = "left_ptr";
            break;
        case VeraCursorShape::IBeam:
            cursorName = "xterm";
            break;
        case VeraCursorShape::Crosshair:
            cursorName = "crosshair";
            break;
        case VeraCursorShape::Hand:
            cursorName = "pointer";
            break;
        case VeraCursorShape::HResize:
            cursorName = "sb_h_double_arrow";
            break;
        case VeraCursorShape::VResize:
            cursorName = "sb_v_double_arrow";
            break;
        case VeraCursorShape::CornerResizeNWSE:
            cursorName = "top_left_corner";
            break;
        case VeraCursorShape::CornerResizeNESW:
            cursorName = "top_right_corner";
            break;
        case VeraCursorShape::NotAllowed:
            cursorName = "not-allowed";
            break;
        default:
            break;
    }

    if (!ctx.cursorTheme) {
        ctx.cursorTheme = wl_cursor_theme_load(nullptr, 24, ctx.shm);
    }
    if (!ctx.cursorTheme) return;

    wl_cursor* cursor = wl_cursor_theme_get_cursor(ctx.cursorTheme, cursorName);
    if (cursor && cursor->image_count > 0) {
        wl_cursor_image* image = cursor->images[0];
        wl_buffer* buffer = wl_cursor_image_get_buffer(image);

        if (!ctx.cursorSurface) {
            ctx.cursorSurface = wl_compositor_create_surface(ctx.compositor);
        }

        // Essential Wayland Order: Attach -> Damage -> Commit -> Set
        wl_surface_attach(ctx.cursorSurface, buffer, 0, 0);
        wl_surface_damage(ctx.cursorSurface, 0, 0, image->width, image->height);
        wl_surface_commit(ctx.cursorSurface);

        // Crucial: Pass the exact live serial received from the callback
        wl_pointer_set_cursor(ctx.pointer, serial, ctx.cursorSurface,
                              image->hotspot_x, image->hotspot_y);
    }
}

// 1. Your app calls this to change state
void setCursorShapeWayland(WaylandContext& ctx, VeraCursorShape shape) {
    ctx.pendingShape = shape;

    // If the pointer is already active inside our surface, update it
    // immediately
    if (ctx.pointer && ctx.pointerSerial != 0) {
        applyCursorToWayland(ctx, ctx.pointerSerial);
    }
}

void setCursorModeWayland(WaylandContext& ctx, wl_surface* surface,
                          VeraCursorMode mode) {
    sCurrentMode = mode;

    if (mode == VeraCursorMode::Disabled) {
        lockPointerWayland(ctx, surface);

        if (ctx.pointer) {
            wl_pointer_set_cursor(ctx.pointer, ctx.pointerSerial, nullptr, 0,
                                  0);
        }
    } else {
        unlockPointerWayland(ctx);

        if (mode == VeraCursorMode::Hidden) {
            if (ctx.pointer) {
                wl_pointer_set_cursor(ctx.pointer, ctx.pointerSerial, nullptr,
                                      0, 0);
            }
        } else {
            setCursorShapeWayland(ctx, VeraCursorShape::Arrow);
        }
    }
}

////////////////////////////////////////////////////////////////////////////////

// Minimal dynamic buffer replacing std::string / std::vector for raw
// binary/text data
struct DynamicBuffer {
    char* data = nullptr;
    size_t length = 0;
    size_t capacity = 0;

    void clear() {
        length = 0;
        if (data) {
            data[0] = '\0';
        }
    }

    void append(const char* src, size_t len) {
        if (!src || len == 0) return;
        if (length + len + 1 > capacity) {
            size_t newCap = (capacity == 0) ? 1024 : capacity * 2;
            while (newCap < length + len + 1) {
                newCap *= 2;
            }
            char* newBuf = static_cast<char*>(realloc(data, newCap));
            if (!newBuf) return;
            data = newBuf;
            capacity = newCap;
        }
        memcpy(data + length, src, len);
        length += len;
        data[length] = '\0';
    }

    void freeMem() {
        if (data) {
            free(data);
            data = nullptr;
        }
        length = 0;
        capacity = 0;
    }
};

static DynamicBuffer gClipboardDataStore;

static const char* kTextMimeTypes[] = {"text/plain;charset=utf-8", "text/plain",
                                       "UTF8_STRING", "STRING"};
constexpr size_t KMIME_TYPE_COUNT =
    sizeof(kTextMimeTypes) / sizeof(kTextMimeTypes[0]);

static void handleSourceTarget(void* data, wl_data_source* source,
                               const char* mime_type) {
    (void)data;
    (void)source;
    (void)mime_type;
}

static void handleSourceSend(void* data, wl_data_source* source,
                             const char* mime_type, int32_t fd) {
    (void)data;
    (void)source;

    bool typeMatches = false;
    for (size_t i = 0; i < KMIME_TYPE_COUNT; ++i) {
        if (mime_type && strcmp(mime_type, kTextMimeTypes[i]) == 0) {
            typeMatches = true;
            break;
        }
    }

    if (typeMatches && fd >= 0) {
        ssize_t written =
            write(fd, gClipboardDataStore.data ? gClipboardDataStore.data : "",
                  gClipboardDataStore.length);
        (void)written;
    }
    close(fd);
}

static void handleSourceCancelled(void* data, wl_data_source* source) {
    (void)data;
    wl_data_source_destroy(source);
}

static const wl_data_source_listener KDATA_SOURCE_LISTENER = {
    .target = handleSourceTarget,
    .send = handleSourceSend,
    .cancelled = handleSourceCancelled,
    .dnd_drop_performed = [](void*, wl_data_source*) {},
    .dnd_finished = [](void*, wl_data_source*) {},
    .action = [](void*, wl_data_source*, uint32_t) {},
};

void initializeClipboardWayland(WaylandContext& ctx) { (void)ctx; }

VeraStringView getClipboardTextWayland(WaylandContext& ctx) {
    if (!ctx.activeClipboardOffer) {
        return {};
    }

    const char* matchedMimeType = "text/plain;charset=utf-8";

    int fds[2];
    if (pipe2(fds, O_CLOEXEC | O_NONBLOCK) < 0) {
        return {};
    }

    wl_data_offer_receive(ctx.activeClipboardOffer, matchedMimeType, fds[1]);
    close(fds[1]);

    wl_display_flush(ctx.display);
    wl_display_roundtrip(ctx.display);

    gClipboardDataStore.clear();
    char buffer[1024];
    struct pollfd pfd = {.fd = fds[0], .events = POLLIN, .revents = 0};

    while (poll(&pfd, 1, 100) > 0) {
        ssize_t bytesRead = read(fds[0], buffer, sizeof(buffer));
        if (bytesRead <= 0) {
            break;
        }
        gClipboardDataStore.append(buffer, bytesRead);
    }

    close(fds[0]);
    return {.data = gClipboardDataStore.data,
            .length = gClipboardDataStore.length};
}

void setClipboardTextWayland(WaylandContext& ctx, const char* text,
                             size_t len) {
    if (!ctx.dataDeviceManager || !ctx.dataDevice) {
        printf("something was still undefined\n");
        return;
    }

    gClipboardDataStore.clear();
    if (text) {
        gClipboardDataStore.append(text, (len > 0) ? len : strlen(text));
    }

    wl_data_source* source =
        wl_data_device_manager_create_data_source(ctx.dataDeviceManager);
    if (!source) {
        return;
    }

    for (size_t i = 0; i < KMIME_TYPE_COUNT; ++i) {
        wl_data_source_offer(source, kTextMimeTypes[i]);
    }

    wl_data_source_add_listener(source, &KDATA_SOURCE_LISTENER, &ctx);

    wl_data_device_set_selection(ctx.dataDevice, source,
                                 ctx.lastPointerButtonSerial);

    wl_display_flush(ctx.display);
}

bool hasClipboardTextWayland(const WaylandContext& ctx) {
    return ctx.activeClipboardOffer != nullptr;
}

/////////////////////////////////////////////////////////////////////////////////////////////

static void decorationHandleConfigure(void* data,
                                      zxdg_toplevel_decoration_v1* decoration,
                                      uint32_t mode) {
    (void)data;
    (void)decoration;
    (void)mode;
#ifdef DEBUG
    if (mode == ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE) {
        printf("[Wayland] Server-side window decorations activated.\n");
    } else {
        printf(
            "[Wayland] Compositor requested Client-Side Decorations (CSD).\n");
    }
#endif
}

static const zxdg_toplevel_decoration_v1_listener KDECORATION_LISTENER = {
    .configure = decorationHandleConfigure};

void initializeDecorationWayland(WaylandContext& ctx) { (void)ctx; }

zxdg_toplevel_decoration_v1* createDecorationWayland(WaylandContext& ctx,
                                                     xdg_toplevel* toplevel) {
    if (!ctx.decorationManager || !toplevel) {
        return nullptr;
    }

    zxdg_toplevel_decoration_v1* decoration =
        zxdg_decoration_manager_v1_get_toplevel_decoration(
            ctx.decorationManager, toplevel);

    if (decoration) {
        zxdg_toplevel_decoration_v1_add_listener(
            decoration, &KDECORATION_LISTENER, nullptr);
        zxdg_toplevel_decoration_v1_set_mode(
            decoration, ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE);
    }

    return decoration;
}

void destroyDecorationWayland(zxdg_toplevel_decoration_v1* decoration) {
    if (decoration) {
        zxdg_toplevel_decoration_v1_destroy(decoration);
    }
}

/////////////////////////////////////////////////////////////////////////////////////////////

static VeraDragCallback gDragCallback = nullptr;
static wl_data_offer* gActiveDndOffer = nullptr;
static double gLastDragX = 0.0;
static double gLastDragY = 0.0;

// In-place URL decoding without heap allocations
static size_t urlDecodeInPlace(char* str) {
    char* src = str;
    char* dst = str;
    while (*src) {
        if (*src == '%' && src[1] && src[2]) {
            int hexVal = 0;
            if (sscanf(src + 1, "%2x", &hexVal) == 1) {
                *dst++ = static_cast<char>(hexVal);
                src += 3;
                continue;
            }
        }
        if (*src == '+') {
            *dst++ = ' ';
            src++;
        } else {
            *dst++ = *src++;
        }
    }
    *dst = '\0';
    return static_cast<size_t>(dst - str);
}

// In-place line scanner populating a pre-allocated VeraStringView array
static size_t parseUriListInPlace(char* payload, VeraStringView* outViews,
                                  size_t maxViews) {
    size_t count = 0;
    char* line = payload;

    while (line && *line && count < maxViews) {
        char* nextLine = strchr(line, '\n');
        if (nextLine) {
            *nextLine = '\0';
        }

        size_t len = strlen(line);
        if (len > 0 && line[len - 1] == '\r') {
            line[len - 1] = '\0';
            len--;
        }

        if (len > 0 && line[0] != '#') {
            if (strncmp(line, "file://", 7) == 0) {
                char* path = line + 7;
                size_t decodedLen = urlDecodeInPlace(path);
                outViews[count].data = path;
                outViews[count].length = decodedLen;
                count++;
            }
        }

        if (!nextLine) break;
        line = nextLine + 1;
    }

    return count;
}

static void handleDragEnter(void* data, wl_data_device* device, uint32_t serial,
                            wl_surface* surface, wl_fixed_t x, wl_fixed_t y,
                            wl_data_offer* offer) {
    (void)data;
    (void)device;
    (void)serial;
    (void)surface;

    gActiveDndOffer = offer;
    gLastDragX = wl_fixed_to_double(x);
    gLastDragY = wl_fixed_to_double(y);

    if (gActiveDndOffer) {
        wl_data_offer_accept(gActiveDndOffer, serial, "text/uri-list");
    }
}

static void handleDragMotion(void* data, wl_data_device* device, uint32_t time,
                             wl_fixed_t x, wl_fixed_t y) {
    (void)data;
    (void)device;
    (void)time;

    gLastDragX = wl_fixed_to_double(x);
    gLastDragY = wl_fixed_to_double(y);
}

static void handleDragLeave(void* data, wl_data_device* device) {
    (void)data;
    (void)device;
    gActiveDndOffer = nullptr;
}

static void handleDragDrop(void* data, wl_data_device* device) {
    auto* ctx = static_cast<WaylandContext*>(data);
    (void)device;

    if (!gActiveDndOffer || !gDragCallback) {
        return;
    }

    int fds[2];
    if (pipe2(fds, O_CLOEXEC | O_NONBLOCK) < 0) {
        return;
    }

    wl_data_offer_receive(gActiveDndOffer, "text/uri-list", fds[1]);
    close(fds[1]);

    wl_display_flush(ctx->display);
    wl_display_roundtrip(ctx->display);

    DynamicBuffer rawPayload;
    char buffer[1024];
    struct pollfd pfd = {.fd = fds[0], .events = POLLIN, .revents = 0};

    while (poll(&pfd, 1, 100) > 0) {
        ssize_t bytesRead = read(fds[0], buffer, sizeof(buffer));
        if (bytesRead <= 0) {
            break;
        }
        rawPayload.append(buffer, bytesRead);
    }
    close(fds[0]);

    if (rawPayload.length > 0) {
        constexpr size_t maxDragPaths = 128;
        VeraStringView viewArray[maxDragPaths];

        size_t pathCount =
            parseUriListInPlace(rawPayload.data, viewArray, maxDragPaths);

        if (pathCount > 0) {
            VeraDragEvent event{};
            event.paths = viewArray;
            event.pathCount = static_cast<uint32_t>(pathCount);
            event.x = gLastDragX;
            event.y = gLastDragY;

            gDragCallback(event);
        }
    }

    rawPayload.freeMem();

    wl_data_offer_finish(gActiveDndOffer);
    gActiveDndOffer = nullptr;
}

static const wl_data_device_listener KDATA_DEVICE_DND_LISTENER = {
    .data_offer = [](void*, wl_data_device*, wl_data_offer*) {},
    .enter = handleDragEnter,
    .leave = handleDragLeave,
    .motion = handleDragMotion,
    .drop = handleDragDrop,
    .selection = [](void*, wl_data_device*, wl_data_offer*) {}};

void initializeDnDWayland(WaylandContext& ctx) {
    if (ctx.dataDevice) {
        wl_data_device_add_listener(ctx.dataDevice, &KDATA_DEVICE_DND_LISTENER,
                                    &ctx);
    }
}

void setDragCallbackWayland(WaylandContext& ctx, VeraDragCallback callback) {
    (void)ctx;
    gDragCallback = callback;
}

void shutdownDnDWayland() {
    gDragCallback = nullptr;
    gActiveDndOffer = nullptr;
    gClipboardDataStore.freeMem();
}

/////////////////////////////////////////////////////////////////////////////////////////////////////

static VeraThemeMode gCurrentThemeMode = VeraThemeMode::Dark;

static VeraThemeMode detectDesktopPreference() {
    const char* gtkThemeEnv = std::getenv("GTK_THEME");
    if (gtkThemeEnv) {
        if (strstr(gtkThemeEnv, "dark") != nullptr ||
            strstr(gtkThemeEnv, "Dark") != nullptr) {
            return VeraThemeMode::Dark;
        }
    }

    const char* homeDir = std::getenv("HOME");
    if (homeDir) {
        char configPath[1024];
        snprintf(configPath, sizeof(configPath),
                 "%s/.config/gtk-3.0/settings.ini", homeDir);

        FILE* file = fopen(configPath, "r");
        if (file) {
            char line[512];
            while (fgets(line, sizeof(line), file)) {
                if (strstr(line, "gtk-application-prefer-dark-theme") !=
                    nullptr) {
                    if (strstr(line, "true") != nullptr ||
                        strstr(line, "1") != nullptr) {
                        fclose(file);
                        return VeraThemeMode::Dark;
                    } else {
                        fclose(file);
                        return VeraThemeMode::Light;
                    }
                }
            }
            fclose(file);
        }
    }

    return VeraThemeMode::Dark;
}

void initializeThemeWayland(WaylandContext& ctx) {
    (void)ctx;
    gCurrentThemeMode = detectDesktopPreference();
    printf("[Theme] Initialized color mode preference: %s \n",
           (gCurrentThemeMode == VeraThemeMode::Dark ? "Dark" : "Light"));
}

VeraThemeMode getActiveThemeModeWayland() { return gCurrentThemeMode; }

void updateThemeWayland() {
    static uint32_t frameCount = 0;
    frameCount++;

    if (frameCount % 300 == 0) {
        VeraThemeMode detected = detectDesktopPreference();
        if (detected != gCurrentThemeMode) {
            gCurrentThemeMode = detected;
            printf(
                "[Theme] Desktop theme changed dynamically to: %s \n",
                (gCurrentThemeMode == VeraThemeMode::Dark ? "Dark" : "Light"));
        }
    }
}

void shutdownThemeWayland() {}

/////////////////////////////////////////////////////////////////////////////////////////

static void processKeyRepeat(WaylandContext* ctx) {
    if (ctx->keyRepeatRate <= 0 || ctx->pressedKeyCount == 0) {
        return;
    }

    uint64_t nowMs = getMonotonicTimeMs();
    uint64_t repeatIntervalMs = 1000ULL / ctx->keyRepeatRate;

    for (size_t i = 0; i < ctx->pressedKeyCount; ++i) {
        auto& repeatState = ctx->pressedKeys[i];
        if (nowMs >= repeatState.nextRepeatMs) {
            if (ctx->focusedWindow && ctx->focusedWindow->getKeyCallback()) {
                ctx->focusedWindow->getKeyCallback()(repeatState.veraKey, true,
                                                     true);
            }

            repeatState.nextRepeatMs = nowMs + repeatIntervalMs;
        }
    }
}

void pollEventsWayland(WaylandContext& ctx,
                       const nostd::Function<bool()>& quitRequestCallback,
                       const nostd::Function<void()>& displayChangeCallback) {
    (void)displayChangeCallback;

    if (!ctx.display) return;

    while (wl_display_prepare_read(ctx.display) != 0) {
        wl_display_dispatch_pending(ctx.display);
    }
    wl_display_flush(ctx.display);

    int fd = wl_display_get_fd(ctx.display);
    struct pollfd pfd = {fd, POLLIN, 0};

    int ret = poll(&pfd, 1, 0);

    if (ret > 0 && (pfd.revents & POLLIN)) {
        wl_display_read_events(ctx.display);
        wl_display_dispatch_pending(ctx.display);
    } else {
        wl_display_cancel_read(ctx.display);
    }

    processKeyRepeat(&ctx);

    if (ctx.quitRequested && quitRequestCallback) {
        if (quitRequestCallback()) {
            ctx.quitRequested = false;
        }
    }
}

void waitForEventsWayland(
    WaylandContext& ctx, const nostd::Function<bool()>& quitRequestCallback,
    const nostd::Function<void()>& displayChangeCallback) {
    (void)displayChangeCallback;

    if (!ctx.display) return;

    wl_display_flush(ctx.display);

    if (wl_display_dispatch(ctx.display) == -1) {
        printf("[Wayland] Connection error on event dispatch loop.\n");
        ctx.quitRequested = true;
    }

    if (ctx.quitRequested && quitRequestCallback) {
        if (quitRequestCallback()) {
            ctx.quitRequested = false;
        }
    }
}

void waitForEventsWithTimeoutWayland(
    WaylandContext& ctx, double timeoutSeconds,
    const nostd::Function<bool()>& quitRequestCallback,
    const nostd::Function<void()>& displayChangeCallback) {
    (void)displayChangeCallback;

    if (!ctx.display) return;

    while (wl_display_prepare_read(ctx.display) != 0) {
        wl_display_dispatch_pending(ctx.display);
    }
    wl_display_flush(ctx.display);

    int fd = wl_display_get_fd(ctx.display);
    struct pollfd pfd = {fd, POLLIN, 0};

    int timeoutMs = static_cast<int>(timeoutSeconds * 1000.0);
    if (timeoutMs < 0) timeoutMs = -1;

    int ret = ::poll(&pfd, 1, timeoutMs);

    if (ret > 0 && (pfd.revents & POLLIN)) {
        wl_display_read_events(ctx.display);
        wl_display_dispatch_pending(ctx.display);
    } else {
        wl_display_cancel_read(ctx.display);
    }

    if (ctx.quitRequested && quitRequestCallback) {
        if (quitRequestCallback()) {
            ctx.quitRequested = false;
        }
    }
}

/////////////////////////////////////////////////////////////////////////////////////////////////

inline static zwp_locked_pointer_v1* sLockedPointer = nullptr;
inline static zwp_relative_pointer_v1* sRelativePointer = nullptr;

static void relativePointerHandleMotion(
    void* data, zwp_relative_pointer_v1* relativePointer, uint32_t time_hi,
    uint32_t time_lo, wl_fixed_t dx, wl_fixed_t dy, wl_fixed_t dx_unaccel,
    wl_fixed_t dy_unaccel) {
    auto* ctx = static_cast<WaylandContext*>(data);
    (void)relativePointer;
    (void)time_hi;
    (void)time_lo;
    (void)dx;
    (void)dy;

    double rawDeltaX = wl_fixed_to_double(dx_unaccel);
    double rawDeltaY = wl_fixed_to_double(dy_unaccel);

    if (ctx->focusedWindow && ctx->focusedWindow->getMouseMoveCallback()) {
        ctx->focusedWindow->getMouseMoveCallback()(rawDeltaX, rawDeltaY);
    }
}

static const zwp_relative_pointer_v1_listener KRELATIVE_POINTER_LISTENER = {
    .relative_motion = relativePointerHandleMotion};

static void lockedPointerHandleLocked(void* data,
                                      zwp_locked_pointer_v1* lockedPointer) {
    (void)data;
    (void)lockedPointer;
#ifdef DEBUG
    std::cout << "[Wayland] Pointer constraint lock acquired.\n";
#endif
}

static void lockedPointerHandleUnlocked(void* data,
                                        zwp_locked_pointer_v1* lockedPointer) {
    (void)data;
    (void)lockedPointer;
#ifdef DEBUG
    std::cout << "[Wayland] Pointer constraint lock released.\n";
#endif
}

static const zwp_locked_pointer_v1_listener KLOCKED_POINTER_LISTENER = {
    .locked = lockedPointerHandleLocked,
    .unlocked = lockedPointerHandleUnlocked};

void unlockPointerWayland(WaylandContext& ctx) {
    (void)ctx;

    if (sRelativePointer) {
        zwp_relative_pointer_v1_destroy(sRelativePointer);
        sRelativePointer = nullptr;
    }

    if (sLockedPointer) {
        zwp_locked_pointer_v1_destroy(sLockedPointer);
        sLockedPointer = nullptr;
    }
}

void lockPointerWayland(WaylandContext& ctx, wl_surface* surface) {
    if (!ctx.pointerConstraints || !ctx.relativePointerManager ||
        !ctx.pointer || !surface) {
        return;
    }

    unlockPointerWayland(ctx);

    sLockedPointer = zwp_pointer_constraints_v1_lock_pointer(
        ctx.pointerConstraints, surface, ctx.pointer, nullptr,
        ZWP_POINTER_CONSTRAINTS_V1_LIFETIME_PERSISTENT);

    if (sLockedPointer) {
        zwp_locked_pointer_v1_add_listener(sLockedPointer,
                                           &KLOCKED_POINTER_LISTENER, &ctx);
    }

    sRelativePointer = zwp_relative_pointer_manager_v1_get_relative_pointer(
        ctx.relativePointerManager, ctx.pointer);

    if (sRelativePointer) {
        zwp_relative_pointer_v1_add_listener(sRelativePointer,
                                             &KRELATIVE_POINTER_LISTENER, &ctx);
    }
}

///////////////////////////////////////////////////////////////////////////////////////////////////////

static nostd::Function<void(uint32_t, uint32_t, bool)> gButtonCallback;
static nostd::Function<void(uint32_t, uint32_t, float)> gAxisCallback;

void setJoystickButtonCallbackWayland(
    nostd::Function<void(uint32_t, uint32_t, bool)> cb) {
    gButtonCallback = cb;
}
void setJoystickAxisCallbackWayland(
    nostd::Function<void(uint32_t, uint32_t, float)> cb) {
    gAxisCallback = cb;
}

void initializeJoystickWayland(WaylandContext& ctx) {
    DIR* devDir = opendir("/dev/input");
    if (!devDir) return;

    struct dirent* entry;
    uint32_t slot = 0;

    while ((entry = readdir(devDir)) != nullptr &&
           slot < std::size(ctx.joysticks)) {
        // Fast prefix check for "js" without strncmp/<cstring>
        if (entry->d_name[0] == 'j' && entry->d_name[1] == 's') {
            // Construct "/dev/input/<d_name>" manually without snprintf
            char path[256] = "/dev/input/";
            size_t pos = 11;  // Length of "/dev/input/"

            for (size_t i = 0;
                 entry->d_name[i] != '\0' && pos < sizeof(path) - 1;
                 ++i, ++pos) {
                path[pos] = entry->d_name[i];
            }
            path[pos] = '\0';

            int fd = open(path, O_RDONLY | O_NONBLOCK);
            if (fd >= 0) {
                JoystickDeviceWayland& joy = ctx.joysticks[slot];
                joy.fd = fd;

                // Copy path string directly into member array
                size_t pIdx = 0;
                while (path[pIdx] != '\0' &&
                       pIdx < sizeof(joy.devicePath) - 1) {
                    joy.devicePath[pIdx] = path[pIdx];
                    pIdx++;
                }
                joy.devicePath[pIdx] = '\0';

                // Set fallback default name directly into target buffer
                const char defaultName[] = "Unknown Controller";
                size_t nIdx = 0;
                while (defaultName[nIdx] != '\0' &&
                       nIdx < sizeof(joy.state.name) - 1) {
                    joy.state.name[nIdx] = defaultName[nIdx];
                    nIdx++;
                }
                joy.state.name[nIdx] = '\0';

                // Pass joy.state.name directly to ioctl - avoids intermediate
                // copies entirely
                ioctl(fd, JSIOCGNAME(sizeof(joy.state.name)), joy.state.name);

                uint8_t axesCount = 0;
                uint8_t buttonsCount = 0;
                ioctl(fd, JSIOCGAXES, &axesCount);
                ioctl(fd, JSIOCGBUTTONS, &buttonsCount);

                joy.state.connected = true;
                joy.state.axes.resize(axesCount, 0.0f);
                joy.state.buttons.resize(buttonsCount, false);

                slot++;
            }
        }
    }
    closedir(devDir);
}

void updateJoystickWayland(WaylandContext& ctx) {
    (void)ctx;

    for (size_t i = 0; i < ctx.joysticks.size(); ++i) {
        JoystickDeviceWayland& joy = ctx.joysticks[i];
        if (joy.fd < 0) continue;

        struct js_event event;
        while (read(joy.fd, &event, sizeof(event)) > 0) {
            uint8_t type = event.type & ~JS_EVENT_INIT;

            if (type == JS_EVENT_BUTTON) {
                if (event.number < joy.state.buttons.size()) {
                    joy.state.buttons[event.number] = (event.value != 0);
                    if (gButtonCallback) {
                        gButtonCallback(static_cast<uint32_t>(i), event.number,
                                        joy.state.buttons[event.number]);
                    }
                }
            } else if (type == JS_EVENT_AXIS) {
                if (event.number < joy.state.axes.size()) {
                    joy.state.axes[event.number] =
                        static_cast<float>(event.value) / 32767.0f;
                    if (gAxisCallback) {
                        gAxisCallback(static_cast<uint32_t>(i), event.number,
                                      joy.state.axes[event.number]);
                    }
                }
            }
        }

        if (errno == ENODEV) {
            printf("[Joystick] Disconnected: %s\n", joy.state.name);
            close(joy.fd);
            joy.fd = -1;
            joy.state.connected = false;
        }
    }
}

VeraJoystickState getStateJoystickWayland(WaylandContext& ctx,
                                          uint32_t joystickId) {
    if (joystickId < ctx.joysticks.size()) {
        return ctx.joysticks[joystickId].state;
    }
    return VeraJoystickState{};
}

void shutdownJoystickWayland(WaylandContext& ctx) {
    (void)ctx;
    for (auto& joy : ctx.joysticks) {
        if (joy.fd >= 0) close(joy.fd);
        joy.fd = -1;
        joy.state.connected = false;
    }
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////

static VeraKey translateScancode(uint32_t scancode) {
    switch (scancode) {
        // Letters (Physical Keys A-Z)
        case KEY_A:
            return VeraKey::A;
        case KEY_B:
            return VeraKey::B;
        case KEY_C:
            return VeraKey::C;
        case KEY_D:
            return VeraKey::D;
        case KEY_E:
            return VeraKey::E;
        case KEY_F:
            return VeraKey::F;
        case KEY_G:
            return VeraKey::G;
        case KEY_H:
            return VeraKey::H;
        case KEY_I:
            return VeraKey::I;
        case KEY_J:
            return VeraKey::J;
        case KEY_K:
            return VeraKey::K;
        case KEY_L:
            return VeraKey::L;
        case KEY_M:
            return VeraKey::M;
        case KEY_N:
            return VeraKey::N;
        case KEY_O:
            return VeraKey::O;
        case KEY_P:
            return VeraKey::P;
        case KEY_Q:
            return VeraKey::Q;
        case KEY_R:
            return VeraKey::R;
        case KEY_S:
            return VeraKey::S;
        case KEY_T:
            return VeraKey::T;
        case KEY_U:
            return VeraKey::U;
        case KEY_V:
            return VeraKey::V;
        case KEY_W:
            return VeraKey::W;
        case KEY_X:
            return VeraKey::X;
        case KEY_Y:
            return VeraKey::Y;
        case KEY_Z:
            return VeraKey::Z;

        // Number Row (Base Unmodified Keys)
        case KEY_0:
            return VeraKey::Num0;
        case KEY_1:
            return VeraKey::Num1;
        case KEY_2:
            return VeraKey::Num2;
        case KEY_3:
            return VeraKey::Num3;
        case KEY_4:
            return VeraKey::Num4;
        case KEY_5:
            return VeraKey::Num5;
        case KEY_6:
            return VeraKey::Num6;
        case KEY_7:
            return VeraKey::Num7;
        case KEY_8:
            return VeraKey::Num8;
        case KEY_9:
            return VeraKey::Num9;

        // Punctuation & Base Symbols
        case KEY_MINUS:
            return VeraKey::Minus;
        case KEY_EQUAL:
            return VeraKey::Equal;
        case KEY_LEFTBRACE:
            return VeraKey::LeftBracket;
        case KEY_RIGHTBRACE:
            return VeraKey::RightBracket;
        case KEY_SEMICOLON:
            return VeraKey::Semicolon;
        case KEY_APOSTROPHE:
            return VeraKey::Apostrophe;
        case KEY_GRAVE:
            return VeraKey::GraveAccent;
        case KEY_BACKSLASH:
            return VeraKey::Backslash;
        case KEY_COMMA:
            return VeraKey::Comma;
        case KEY_DOT:
            return VeraKey::Period;
        case KEY_SLASH:
            return VeraKey::Slash;
        case KEY_SPACE:
            return VeraKey::Space;

        // System & Editing Controls
        case KEY_ESC:
            return VeraKey::Escape;
        case KEY_ENTER:
            return VeraKey::Enter;
        case KEY_TAB:
            return VeraKey::Tab;
        case KEY_BACKSPACE:
            return VeraKey::Backspace;
        case KEY_INSERT:
            return VeraKey::Insert;
        case KEY_DELETE:
            return VeraKey::Delete;
        case KEY_HOME:
            return VeraKey::Home;
        case KEY_END:
            return VeraKey::End;
        case KEY_PAGEUP:
            return VeraKey::PageUp;
        case KEY_PAGEDOWN:
            return VeraKey::PageDown;

        // Navigation Arrows
        case KEY_LEFT:
            return VeraKey::Left;
        case KEY_RIGHT:
            return VeraKey::Right;
        case KEY_UP:
            return VeraKey::Up;
        case KEY_DOWN:
            return VeraKey::Down;

        // Modifiers
        case KEY_LEFTSHIFT:
            return VeraKey::LeftShift;
        case KEY_RIGHTSHIFT:
            return VeraKey::RightShift;
        case KEY_LEFTCTRL:
            return VeraKey::LeftCtrl;
        case KEY_RIGHTCTRL:
            return VeraKey::RightCtrl;
        case KEY_LEFTALT:
            return VeraKey::LeftAlt;
        case KEY_RIGHTALT:
            return VeraKey::RightAlt;
        case KEY_LEFTMETA:
            return VeraKey::LeftSuper;
        case KEY_RIGHTMETA:
            return VeraKey::RightSuper;

        // Locks & Utility
        case KEY_CAPSLOCK:
            return VeraKey::CapsLock;
        case KEY_SCROLLLOCK:
            return VeraKey::ScrollLock;
        case KEY_NUMLOCK:
            return VeraKey::NumLock;
        case KEY_PRINT:
            return VeraKey::PrintScreen;
        case KEY_PAUSE:
            return VeraKey::Pause;
        case KEY_COMPOSE:
            return VeraKey::Menu;

        // Function Keys
        case KEY_F1:
            return VeraKey::F1;
        case KEY_F2:
            return VeraKey::F2;
        case KEY_F3:
            return VeraKey::F3;
        case KEY_F4:
            return VeraKey::F4;
        case KEY_F5:
            return VeraKey::F5;
        case KEY_F6:
            return VeraKey::F6;
        case KEY_F7:
            return VeraKey::F7;
        case KEY_F8:
            return VeraKey::F8;
        case KEY_F9:
            return VeraKey::F9;
        case KEY_F10:
            return VeraKey::F10;
        case KEY_F11:
            return VeraKey::F11;
        case KEY_F12:
            return VeraKey::F12;

        // Keypad
        case KEY_KP0:
            return VeraKey::KP0;
        case KEY_KP1:
            return VeraKey::KP1;
        case KEY_KP2:
            return VeraKey::KP2;
        case KEY_KP3:
            return VeraKey::KP3;
        case KEY_KP4:
            return VeraKey::KP4;
        case KEY_KP5:
            return VeraKey::KP5;
        case KEY_KP6:
            return VeraKey::KP6;
        case KEY_KP7:
            return VeraKey::KP7;
        case KEY_KP8:
            return VeraKey::KP8;
        case KEY_KP9:
            return VeraKey::KP9;
        case KEY_KPDOT:
            return VeraKey::KPDecimal;
        case KEY_KPSLASH:
            return VeraKey::KPDivide;
        case KEY_KPASTERISK:
            return VeraKey::KPMultiply;
        case KEY_KPMINUS:
            return VeraKey::KPSubtract;
        case KEY_KPPLUS:
            return VeraKey::KPAdd;
        case KEY_KPENTER:
            return VeraKey::KPEnter;
        case KEY_KPEQUAL:
            return VeraKey::KPEqual;

        // Media Controls
        case KEY_VOLUMEUP:
            return VeraKey::VolumeUp;
        case KEY_VOLUMEDOWN:
            return VeraKey::VolumeDown;
        case KEY_MUTE:
            return VeraKey::Mute;

        default:
            return VeraKey::Unknown;
    }
}

static void keyboardHandleKeymap(void* data, wl_keyboard* keyboard,
                                 uint32_t format, int32_t fd, uint32_t size) {
    auto* ctx = static_cast<WaylandContext*>(data);
    (void)keyboard;

    if (format != WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1) {
        close(fd);
        return;
    }

    char* mapStr =
        static_cast<char*>(mmap(nullptr, size, PROT_READ, MAP_SHARED, fd, 0));
    if (mapStr == MAP_FAILED) {
        close(fd);
        return;
    }

    if (!ctx->xkbContext) {
        ctx->xkbContext = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
    }

    if (ctx->xkbKeymap) xkb_keymap_unref(ctx->xkbKeymap);
    ctx->xkbKeymap = xkb_keymap_new_from_string(ctx->xkbContext, mapStr,
                                                XKB_KEYMAP_FORMAT_TEXT_V1,
                                                XKB_KEYMAP_COMPILE_NO_FLAGS);
    munmap(mapStr, size);
    close(fd);

    if (ctx->xkbKeymap) {
        if (ctx->xkbState) xkb_state_unref(ctx->xkbState);
        ctx->xkbState = xkb_state_new(ctx->xkbKeymap);
    }
}

static void keyboardHandleEnter(void* data, wl_keyboard* keyboard,
                                uint32_t serial, wl_surface* surface,
                                wl_array* keys) {
    auto* ctx = static_cast<WaylandContext*>(data);
    (void)keyboard;
    (void)serial;
    (void)keys;

    ctx->focusedWindow = ctx->findWindowBySurface(surface);
}

static void keyboardHandleLeave(void* data, wl_keyboard* keyboard,
                                uint32_t serial, wl_surface* surface) {
    auto* ctx = static_cast<WaylandContext*>(data);
    (void)keyboard;
    (void)serial;
    (void)surface;
    ctx->focusedWindow = nullptr;
}

static void keyboardHandleKey(void* data, wl_keyboard* keyboard,
                              uint32_t serial, uint32_t time, uint32_t key,
                              uint32_t state) {
    auto* ctx = static_cast<WaylandContext*>(data);
    (void)keyboard;
    (void)serial;
    (void)time;

    if (!ctx->focusedWindow || !ctx->xkbState) return;

    auto* win = ctx->focusedWindow;
    uint32_t scanCode = key + 8;

    VeraKey veraKey = translateScancode(key);
    bool pressed = (state == WL_KEYBOARD_KEY_STATE_PRESSED);

    constexpr size_t totalKeyStates =
        sizeof(ctx->keyStates) / sizeof(ctx->keyStates[0]);

    // Update central state tracking array before firing callbacks
    if (veraKey != VeraKey::Unknown && veraKey != VeraKey::Count) {
        size_t keyIndex = static_cast<size_t>(veraKey);
        if (keyIndex < totalKeyStates) {
            ctx->keyStates[keyIndex] = pressed;
        }
    }

    if (pressed) {
        uint64_t nextRepeatMs = getMonotonicTimeMs() + ctx->keyRepeatDelay;

        // Check if key is already in key repeat list
        bool found = false;
        for (size_t i = 0; i < ctx->pressedKeyCount; ++i) {
            if (ctx->pressedKeys[i].key == key) {
                ctx->pressedKeys[i].scanCode = scanCode;
                ctx->pressedKeys[i].veraKey = veraKey;
                ctx->pressedKeys[i].nextRepeatMs = nextRepeatMs;
                found = true;
                break;
            }
        }

        // Append to key repeat array if new
        if (!found && ctx->pressedKeyCount < MAX_KEY_REPEATS) {
            ctx->pressedKeys[ctx->pressedKeyCount++] = {
                .key = key,
                .scanCode = scanCode,
                .veraKey = veraKey,
                .nextRepeatMs = nextRepeatMs};
        }
    } else {
        // Swap-and-pop removal from flat array
        for (size_t i = 0; i < ctx->pressedKeyCount; ++i) {
            if (ctx->pressedKeys[i].key == key) {
                VeraKey originalKey = ctx->pressedKeys[i].veraKey;
                if (originalKey != veraKey) {
                    size_t origIndex = static_cast<size_t>(originalKey);
                    if (origIndex < totalKeyStates) {
                        ctx->keyStates[origIndex] = false;
                    }
                    veraKey = originalKey;
                }

                ctx->pressedKeys[i] =
                    ctx->pressedKeys[ctx->pressedKeyCount - 1];
                ctx->pressedKeys[--ctx->pressedKeyCount] = {};
                break;
            }
        }
    }

    // Fire application key callback
    if (win->getKeyCallback()) {
        win->getKeyCallback()(veraKey, pressed, false);
    }

    // Process Text Input via xkbcommon directly into stack buffer
    if (pressed && win->getCharCallback()) {
        char buffer[8] = {0};
        int size = xkb_state_key_get_utf8(ctx->xkbState, scanCode, buffer,
                                          sizeof(buffer));
        if (size > 0) {
            win->getCharCallback()(buffer);
        }
    }
}

static void keyboardHandleModifiers(void* data, wl_keyboard* keyboard,
                                    uint32_t serial, uint32_t mods_depressed,
                                    uint32_t mods_latched, uint32_t mods_locked,
                                    uint32_t group) {
    auto* ctx = static_cast<WaylandContext*>(data);
    (void)keyboard;
    (void)serial;

    if (ctx->xkbState) {
        xkb_state_update_mask(ctx->xkbState, mods_depressed, mods_latched,
                              mods_locked, 0, 0, group);
    }
}

static void keyboardHandleRepeatInfo(void* data, wl_keyboard* keyboard,
                                     int32_t rate, int32_t delay) {
    auto* ctx = static_cast<WaylandContext*>(data);

    (void)keyboard;
    ctx->keyRepeatRate = ctx->keyRepeatRate ? ctx->keyRepeatRate : rate;
    ctx->keyRepeatDelay = ctx->keyRepeatDelay ? ctx->keyRepeatDelay : delay;
}

const wl_keyboard_listener KKEYBOARD_LISTENER = {
    .keymap = keyboardHandleKeymap,
    .enter = keyboardHandleEnter,
    .leave = keyboardHandleLeave,
    .key = keyboardHandleKey,
    .modifiers = keyboardHandleModifiers,
    .repeat_info = keyboardHandleRepeatInfo};

void addListenerToKeyboard(WaylandContext& ctx, wl_keyboard* keyboard) {
    if (keyboard) {
        wl_keyboard_add_listener(keyboard, &KKEYBOARD_LISTENER, &ctx);
    }
}

///////////////////////////////////////////////////////////////////////////////////////////////////////

static double sPointerX = 0.0;
static double sPointerY = 0.0;
static WaylandWindow* sPointerTargetWindow = nullptr;

static VeraMouseButton translateMouseButton(uint32_t button) {
    switch (button) {
        case BTN_LEFT:
            return VeraMouseButton::Left;
        case BTN_RIGHT:
            return VeraMouseButton::Right;
        case BTN_MIDDLE:
            return VeraMouseButton::Middle;
        case BTN_SIDE:
            return VeraMouseButton::VeraButton4;
        case BTN_EXTRA:
            return VeraMouseButton::VeraButton5;
        default:
            return VeraMouseButton::Count;
    }
}

static void pointerHandleEnter(void* data, wl_pointer* pointer, uint32_t serial,
                               wl_surface* surface, wl_fixed_t sx,
                               wl_fixed_t sy) {
    auto* ctx = static_cast<WaylandContext*>(data);

    // 1. Un-suppress and map input arguments to the operational context
    ctx->pointer = pointer;
    ctx->pointerSerial = serial;

    WaylandWindow* window = ctx->findWindowBySurface(surface);
    if (window) {
        sPointerTargetWindow = window;
        sPointerX = wl_fixed_to_double(sx);
        sPointerY = wl_fixed_to_double(sy);
    }

    // 2. Commit your stored cursor configuration with the active validation
    // token
    applyCursorToWayland(*ctx, serial);
}

static void pointerHandleLeave(void* data, wl_pointer* pointer, uint32_t serial,
                               wl_surface* surface) {
    auto* ctx = static_cast<WaylandContext*>(data);
    (void)pointer;
    (void)serial;
    (void)surface;

    // Invalidate state mapping flags
    sPointerTargetWindow = nullptr;
    if (ctx) {
        ctx->pointerSerial = 0;
    }
}

static void pointerHandleMotion(void* data, wl_pointer* pointer, uint32_t time,
                                wl_fixed_t sx, wl_fixed_t sy) {
    (void)data;
    (void)pointer;
    (void)time;
    sPointerX = wl_fixed_to_double(sx);
    sPointerY = wl_fixed_to_double(sy);
}

static void pointerHandleButton(void* data, wl_pointer* pointer,
                                uint32_t serial, uint32_t time, uint32_t button,
                                uint32_t state) {
    auto* ctx = static_cast<WaylandContext*>(data);
    (void)pointer;
    (void)time;

    // Capture the valid user input serial for actions like clipboard selection
    if (ctx) {
        ctx->lastPointerButtonSerial = serial;
    }

    if (!sPointerTargetWindow) return;

    // Optional but recommended: Update pointer token on structural button
    // presses
    if (ctx) {
        ctx->pointerSerial = serial;
    }

    VeraMouseButton veraButton = translateMouseButton(button);
    bool pressed = (state == WL_POINTER_BUTTON_STATE_PRESSED);

    if (sPointerTargetWindow->getMouseButtonCallback()) {
        sPointerTargetWindow->getMouseButtonCallback()(veraButton, pressed);
    }
}

static void pointerHandleAxis(void* data, wl_pointer* pointer, uint32_t time,
                              uint32_t axis, wl_fixed_t value) {
    (void)data;
    (void)pointer;
    (void)time;

    if (!sPointerTargetWindow) return;

    double scrollVal = wl_fixed_to_double(value);
    double normScroll = -scrollVal / 10.0;

    if (sPointerTargetWindow->getScrollCallback()) {
        if (axis == WL_POINTER_AXIS_VERTICAL_SCROLL) {
            sPointerTargetWindow->getScrollCallback()(0.0, normScroll);
        } else if (axis == WL_POINTER_AXIS_HORIZONTAL_SCROLL) {
            sPointerTargetWindow->getScrollCallback()(normScroll, 0.0);
        }
    }
}

static void pointerHandleFrame(void* data, wl_pointer* pointer) {
    (void)data;
    (void)pointer;

    if (sPointerTargetWindow && sPointerTargetWindow->getMouseMoveCallback()) {
        sPointerTargetWindow->getMouseMoveCallback()(sPointerX, sPointerY);
    }
}

static void pointerHandleAxisSource(void* data, wl_pointer* pointer,
                                    uint32_t axis_source) {
    (void)data;
    (void)pointer;
    (void)axis_source;
}

static void pointerHandleAxisStop(void* data, wl_pointer* pointer,
                                  uint32_t time, uint32_t axis) {
    (void)data;
    (void)pointer;
    (void)time;
    (void)axis;
}

static void pointerHandleAxisDiscrete(void* data, wl_pointer* pointer,
                                      uint32_t axis, int32_t discrete) {
    (void)data;
    (void)pointer;
    (void)axis;
    (void)discrete;
}

static const wl_pointer_listener KPOINTER_LISTENER = {
    .enter = pointerHandleEnter,
    .leave = pointerHandleLeave,
    .motion = pointerHandleMotion,
    .button = pointerHandleButton,
    .axis = pointerHandleAxis,
    .frame = pointerHandleFrame,
    .axis_source = pointerHandleAxisSource,
    .axis_stop = pointerHandleAxisStop,
    .axis_discrete = pointerHandleAxisDiscrete,
    .axis_value120 = nullptr,
    .axis_relative_direction = nullptr,
    .warp = nullptr,
};

void addListenerToPointer(WaylandContext& ctx, wl_pointer* pointer) {
    if (pointer) {
        wl_pointer_add_listener(pointer, &KPOINTER_LISTENER, &ctx);
    }
}

nostd::Vector<VeraMonitorInfo> getMonitorsWayland(const WaylandContext& ctx) {
    nostd::Vector<VeraMonitorInfo> list;
    list.reserve(ctx.outputCount);

    for (const auto& out : ctx.outputs) {
        VeraMonitorInfo info{};
        info.name = !out.name ? "Generic Wayland Display" : out.name;

        info.x = out.x;
        info.y = out.y;

        info.workAreaX = out.x;
        info.workAreaY = out.y;
        info.workAreaWidth = (out.widthMm > 0) ? out.widthMm : 1920;
        info.workAreaHeight = (out.heightMm > 0) ? out.heightMm : 1080;

        info.dpiScale = static_cast<float>(out.scaleFactor);

        info.refreshRateHz = static_cast<uint32_t>(out.refreshRate / 1000);
        info.isPrimary = out.isPrimary;

        if (out.widthMm > 0 && out.heightMm > 0) {
            info.physicalWidthMm = static_cast<uint32_t>(out.widthMm);
            info.physicalHeightMm = static_cast<uint32_t>(out.heightMm);
        }

        list.push_back(info);
    }

    return list;
}

VeraMonitorInfo getPrimaryMonitorWayland(const WaylandContext& ctx) {
    for (const auto& out : ctx.outputs) {
        if (out.isPrimary) {
            auto monitors = getMonitorsWayland(ctx);
            for (const auto& m : monitors) {
                if (m.name == out.name) return m;
            }
        }
    }

    auto monitors = getMonitorsWayland(ctx);
    if (!monitors.empty()) {
        return monitors.front();
    }

    return VeraMonitorInfo{};
}

VeraMonitorInfo getMonitorAtCoordinateXYWayland(const WaylandContext& ctx,
                                                int32_t x, int32_t y) {
    auto monitors = getMonitorsWayland(ctx);
    if (monitors.empty()) return VeraMonitorInfo{};

    for (const auto& monitor : monitors) {
        if (x >= monitor.x &&
            x < (monitor.x + static_cast<int32_t>(monitor.workAreaWidth)) &&
            y >= monitor.y &&
            y < (monitor.y + static_cast<int32_t>(monitor.workAreaHeight))) {
            return monitor;
        }
    }

    return monitors.front();
}

nostd::Vector<VeraDisplayModeInfo> getSupportedDisplayModesWayland(
    const WaylandContext& ctx, const VeraMonitorInfo& monitor) {
    nostd::Vector<VeraDisplayModeInfo> modes;

    for (const auto& out : ctx.outputs) {
        if (out.name == monitor.name) {
            VeraDisplayModeInfo mode{};
            mode.width = monitor.workAreaWidth;
            mode.height = monitor.workAreaHeight;
            mode.refreshRateHz = static_cast<uint32_t>(out.refreshRate / 1000);
            mode.bitsPerPixel = 32;
            modes.push_back(mode);
            break;
        }
    }

    return modes;
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////

static int createAnonymousFile(off_t size) {
    int fd = memfd_create("vera-shm", MFD_CLOEXEC);
    if (fd < 0) return -1;
    if (ftruncate(fd, size) < 0) {
        close(fd);
        return -1;
    }
    return fd;
}

struct WaylandBuffer {
    wl_buffer* wlBuffer = nullptr;
    void* data = nullptr;
    size_t size = 0;
};

static WaylandBuffer createFallbackBuffer(wl_shm* shm, int width, int height) {
    WaylandBuffer buffer;
    if (!shm || width <= 0 || height <= 0) return buffer;

    int stride = width * 4;
    buffer.size = stride * height;

    int fd = createAnonymousFile(buffer.size);
    if (fd < 0) return buffer;

    buffer.data =
        mmap(nullptr, buffer.size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (buffer.data == MAP_FAILED) {
        close(fd);
        return buffer;
    }

    std::memset(buffer.data, 0x1A, buffer.size);

    wl_shm_pool* pool = wl_shm_create_pool(shm, fd, buffer.size);
    buffer.wlBuffer = wl_shm_pool_create_buffer(pool, 0, width, height, stride,
                                                WL_SHM_FORMAT_XRGB8888);

    wl_shm_pool_destroy(pool);
    close(fd);

    return buffer;
}

// INFO: Left the comments to understand it later
// Internal tracking set to identify surfaces bound to a GPU API (Vulkan/EGL)
// This requires zero header file changes and safely isolates the race
// condition.
constexpr size_t MAX_TAINTED_SURFACES = 64;
static wl_surface* gGraphicsTaintedSurfaces[MAX_TAINTED_SURFACES] = {nullptr};
static size_t gGraphicsTaintedCount = 0;

static bool isSurfaceTainted(wl_surface* surface) {
    if (!surface) return false;
    for (size_t i = 0; i < gGraphicsTaintedCount; ++i) {
        if (gGraphicsTaintedSurfaces[i] == surface) {
            return true;
        }
    }
    return false;
}

void markSurfaceGraphicsTainted(wl_surface* surface) {
    if (!surface || isSurfaceTainted(surface)) return;
    if (gGraphicsTaintedCount < MAX_TAINTED_SURFACES) {
        gGraphicsTaintedSurfaces[gGraphicsTaintedCount++] = surface;
    }
}

void unmarkSurfaceGraphicsTainted(wl_surface* surface) {
    for (size_t i = 0; i < gGraphicsTaintedCount; ++i) {
        if (gGraphicsTaintedSurfaces[i] == surface) {
            // Swap with last element for O(1) removal
            gGraphicsTaintedSurfaces[i] =
                gGraphicsTaintedSurfaces[gGraphicsTaintedCount - 1];
            gGraphicsTaintedSurfaces[--gGraphicsTaintedCount] = nullptr;
            return;
        }
    }
}

static void xdgSurfaceHandleConfigure(void* data, xdg_surface* xdgSurface,
                                      uint32_t serial) {
    // INFO: Left the comments
    auto* window = static_cast<WaylandWindow*>(data);

    // Always acknowledge the configuration transaction immediately
    xdg_surface_ack_configure(xdgSurface, serial);

    // Check if this window has bound a graphics context or has had its native
    // handle requested by a GPU subsystem (like Vulkan WSI)
    bool isGpuSurface =
        window->hasGraphicsContext() || isSurfaceTainted(window->surface());

    if (isGpuSurface) {
        // GPU Mode: Never attach SHM fallback buffers. A bare commit is 100%
        // valid and safely avoids explicit sync timeline errors (Error 4).
        if (window->hasActiveGraphicsBuffer()) {
            window->triggerResizeCallback();
        } else {
            wl_surface_commit(window->surface());
        }
    } else {
        // Pure CPU/Software Path: Explicit sync is not engaged on this surface,
        // making it completely safe to attach and commit an SHM fallback
        // buffer.
        WaylandBuffer fallback = createFallbackBuffer(
            window->context().shm, window->width(), window->height());
        if (fallback.wlBuffer) {
            wl_surface_attach(window->surface(), fallback.wlBuffer, 0, 0);
            wl_surface_damage(window->surface(), 0, 0, window->width(),
                              window->height());
            window->setFallbackBuffer(fallback.wlBuffer);
            wl_surface_commit(window->surface());
        }
    }
}

static const xdg_surface_listener KXDG_SURFACE_LISTENER = {
    .configure = xdgSurfaceHandleConfigure};

static void xdgToplevelHandleConfigure(void* data, xdg_toplevel* xdgToplevel,
                                       int32_t width, int32_t height,
                                       wl_array* states) {
    auto* window = static_cast<WaylandWindow*>(data);
    (void)xdgToplevel;
    window->handleConfigure(width, height, states);
}

static void xdgToplevelHandleClose(void* data, xdg_toplevel* xdgToplevel) {
    auto* window = static_cast<WaylandWindow*>(data);
    (void)xdgToplevel;
    window->handleWmCloseRequest();
}

static const xdg_toplevel_listener KXDG_TOP_LEVEL_LISTENER = {
    .configure = xdgToplevelHandleConfigure,
    .close = xdgToplevelHandleClose,
    .configure_bounds = nullptr,
    .wm_capabilities = nullptr};

WaylandWindow::WaylandWindow(WaylandContext& ctx, VeraWindowHandle handle,
                             const VeraWindowInfo& info)
    : m_ctx(ctx),
      m_handle(handle),
      m_isResizing(false),
      m_pendingDeletion(false),
      m_hasGraphicsContext(false) {
    m_width = info.width;
    m_height = info.height;
    initSurface(info);
}

WaylandWindow::~WaylandWindow() { destroySurface(); }

void WaylandWindow::initSurface(const VeraWindowInfo& info) {
    if (!m_ctx.compositor || !m_ctx.wmBase) return;
    m_isResizing = false;
    m_surface = wl_compositor_create_surface(m_ctx.compositor);
    if (!m_surface) return;

    // Defensively resolve the monitor scale factor
    auto monitorInfo = getPrimaryMonitorWayland(m_ctx);

    int32_t scale = static_cast<int32_t>(std::ceil(monitorInfo.dpiScale));

    // STRICT GUARD: Wayland protocol will instantly crash if scale < 1
    if (scale < 1) {
        scale = 1;
    }

    wl_surface_set_buffer_scale(m_surface, 1);

    m_ctx.registerWindowSurface(m_surface, this);

    m_xdgSurface = xdg_wm_base_get_xdg_surface(m_ctx.wmBase, m_surface);
    if (!m_xdgSurface) return;
    xdg_surface_add_listener(m_xdgSurface, &KXDG_SURFACE_LISTENER, this);

    m_xdgToplevel = xdg_surface_get_toplevel(m_xdgSurface);
    if (!m_xdgToplevel) return;
    xdg_toplevel_add_listener(m_xdgToplevel, &KXDG_TOP_LEVEL_LISTENER, this);

    xdg_toplevel_set_title(m_xdgToplevel, info.title);
    xdg_toplevel_set_app_id(m_xdgToplevel, "VeraEngine");

    m_decoration = createDecorationWayland(m_ctx, m_xdgToplevel);

    wl_surface_commit(m_surface);
}

void addKeyRepeat(WaylandContext& ctx, uint32_t key, uint32_t scanCode,
                  VeraKey veraKey, uint64_t delayMs) {
    uint64_t now = getMonotonicTimeMs();
    for (size_t i = 0; i < ctx.pressedKeyCount; ++i) {
        if (ctx.pressedKeys[i].key == key) {
            ctx.pressedKeys[i].nextRepeatMs = now + delayMs;
            return;
        }
    }
    if (ctx.pressedKeyCount < MAX_KEY_REPEATS) {
        ctx.pressedKeys[ctx.pressedKeyCount++] = {key, scanCode, veraKey,
                                                  now + delayMs};
    }
}

void removeKeyRepeat(WaylandContext& ctx, uint32_t key) {
    for (size_t i = 0; i < ctx.pressedKeyCount; ++i) {
        if (ctx.pressedKeys[i].key == key) {
            ctx.pressedKeys[i] = ctx.pressedKeys[ctx.pressedKeyCount - 1];
            ctx.pressedKeys[--ctx.pressedKeyCount] = {};
            return;
        }
    }
}

void WaylandWindow::destroySurface() {
    m_keyCallback = {};
    m_mouseButtonCallback = {};
    m_mouseMoveCallback = {};
    m_scrollCallback = {};
    m_charCallback = {};

    if (m_ctx.focusedWindow == this) {
        m_ctx.focusedWindow = nullptr;
        m_ctx.keyboardFocusSurface = nullptr;
    }

    if (m_ctx.pointerFocusSurface == m_surface) {
        m_ctx.pointerFocusSurface = nullptr;
    }

    m_ctx.pressedKeyCount = 0;

    if (m_fallbackBuffer) {
        wl_buffer_destroy(m_fallbackBuffer);
        m_fallbackBuffer = nullptr;
    }

    if (m_surface) {
        unmarkSurfaceGraphicsTainted(m_surface);
        // gGraphicsTaintedSurfaces.erase(m_surface);
        m_ctx.unregisterWindowSurface(m_surface);
    }

    if (m_decoration) {
        destroyDecorationWayland(m_decoration);
        m_decoration = nullptr;
    }

    if (m_xdgToplevel) {
        xdg_toplevel_destroy(m_xdgToplevel);
        m_xdgToplevel = nullptr;
    }

    if (m_xdgSurface) {
        xdg_surface_destroy(m_xdgSurface);
        m_xdgSurface = nullptr;
    }

    if (m_surface) {
        wl_surface_destroy(m_surface);
        m_surface = nullptr;
    }
}

VeraWindowHandle WaylandWindow::getHandle() const { return m_handle; }

VeraNativeHandle WaylandWindow::getNativeHandle() const {
    VeraNativeHandle handle{};
    handle.display = m_ctx.display;
    handle.waylandSurface = m_surface;

    // As soon as a graphics context initialization requests the raw surface
    // handle, we flag it so the configuration callback knows explicit sync
    // rules apply.
    if (m_surface) {
        markSurfaceGraphicsTainted(m_surface);
        // gGraphicsTaintedSurfaces.insert(m_surface);
    }
    return handle;
}

void WaylandWindow::setSize(uint32_t width, uint32_t height) {
    m_width = width;
    m_height = height;
    if (m_resizeCallback) m_resizeCallback(width, height);
}

void WaylandWindow::setPosition(int32_t x, int32_t y) {
    (void)x;
    (void)y;
}

void WaylandWindow::setMinSize(uint32_t width, uint32_t height) {
    if (m_xdgToplevel) {
        xdg_toplevel_set_min_size(m_xdgToplevel, static_cast<int32_t>(width),
                                  static_cast<int32_t>(height));
        if (!m_hasGraphicsContext) {
            wl_surface_commit(m_surface);
        }
    }
}

void WaylandWindow::setMaxSize(uint32_t width, uint32_t height) {
    if (m_xdgToplevel) {
        xdg_toplevel_set_max_size(m_xdgToplevel, static_cast<int32_t>(width),
                                  static_cast<int32_t>(height));
        if (!m_hasGraphicsContext) {
            wl_surface_commit(m_surface);
        }
    }
}

VeraWindowState WaylandWindow::getState() const { return m_state; }

void WaylandWindow::show() {
    if (!m_hasGraphicsContext) {
        wl_surface_commit(m_surface);
    }
}

void WaylandWindow::hide() { destroySurface(); }

void WaylandWindow::minimize() {
    if (m_xdgToplevel) {
        xdg_toplevel_set_minimized(m_xdgToplevel);
    }
}

void WaylandWindow::maximize() {
    if (m_xdgToplevel) {
        xdg_toplevel_set_maximized(m_xdgToplevel);
    }
}

void WaylandWindow::restore() {
    if (m_xdgToplevel) {
        xdg_toplevel_unset_maximized(m_xdgToplevel);
    }
}

void WaylandWindow::close() { handleWmCloseRequest(); }

void WaylandWindow::handleWmCloseRequest() {
    if (m_closeRequestCallback) {
        if (!m_closeRequestCallback()) return;
    }

    m_pendingDeletion = true;
}

void WaylandWindow::focus() {}

void WaylandWindow::setTitle(const char* title) {
    if (m_xdgToplevel) {
        xdg_toplevel_set_title(m_xdgToplevel, title);
    }
}

void WaylandWindow::setFullscreen(FullScreenMode mode) {
    if (!m_xdgToplevel) return;

    if (mode != FullScreenMode::Windowed) {
        xdg_toplevel_set_fullscreen(m_xdgToplevel, nullptr);
    } else {
        xdg_toplevel_unset_fullscreen(m_xdgToplevel);
    }

    if (!m_hasGraphicsContext) {
        wl_surface_commit(m_surface);
    }
}

void WaylandWindow::setAlwaysOnTop(bool value) { (void)value; }

void WaylandWindow::setIcon(const char* iconPath) { (void)iconPath; }

void WaylandWindow::setTitlebarHitTestRegions(
    const VeraHitTestRegions& regions) {
    m_hitTestRegions = regions;
}

void WaylandWindow::setResizeCallback(
    nostd::Function<void(uint32_t, uint32_t)> callback) {
    m_resizeCallback = callback;
}
void WaylandWindow::setMoveCallback(
    nostd::Function<void(int32_t, int32_t)> callback) {
    m_moveCallback = callback;
}
void WaylandWindow::setCloseRequestCallback(nostd::Function<bool()> callback) {
    m_closeRequestCallback = callback;
}
void WaylandWindow::setFocusChangeCallback(
    nostd::Function<void(bool)> callback) {
    m_focusChangeCallback = callback;
}
void WaylandWindow::setDpiChangeCallback(
    nostd::Function<void(float)> callback) {
    m_dpiChangeCallback = callback;
}
void WaylandWindow::setKeyCallback(
    nostd::Function<void(VeraKey, bool, bool)> callback) {
    m_keyCallback = callback;
}
void WaylandWindow::setMouseButtonCallback(
    nostd::Function<void(VeraMouseButton, bool)> callback) {
    m_mouseButtonCallback = callback;
}
void WaylandWindow::setMouseMoveCallback(
    nostd::Function<void(double, double)> callback) {
    m_mouseMoveCallback = callback;
}
void WaylandWindow::setScrollCallback(
    nostd::Function<void(double, double)> callback) {
    m_scrollCallback = callback;
}
void WaylandWindow::setCharCallback(
    nostd::Function<void(const char*)> callback) {
    m_charCallback = callback;
}

void WaylandWindow::setCursorMode(VeraCursorMode mode) {
    setCursorModeWayland(m_ctx, m_surface, mode);
}

void WaylandWindow::setCursorShape(VeraCursorShape shape) {
    setCursorShapeWayland(m_ctx, shape);
}

VeraMonitorInfo WaylandWindow::getCurrentMonitor() const {
    return getPrimaryMonitorWayland(m_ctx);
}

void WaylandWindow::handleConfigure(int32_t width, int32_t height,
                                    wl_array* states) {
    m_isResizing = false;

    if (states && states->size > 0) {
        const auto* dataBegin = static_cast<const uint32_t*>(states->data);
        const size_t numElements = states->size / sizeof(uint32_t);

        for (size_t i = 0; i < numElements; ++i) {
            if (dataBegin[i] == XDG_TOPLEVEL_STATE_RESIZING) {
                m_isResizing = true;
                break;
            }
        }
    }

    if (width > 0 && height > 0) {
        m_state.width = static_cast<uint32_t>(width);
        m_state.height = static_cast<uint32_t>(height);

        if (m_resizeCallback) {
            m_resizeCallback(m_state.width, m_state.height);
        }
    }
}

void WaylandWindow::triggerResizeCallback() {
    if (m_resizeCallback) {
        m_resizeCallback(m_state.width, m_state.height);
    }
}

void WaylandWindow::markGraphicsContextActive() {
    m_hasGraphicsContext = true;
    if (m_fallbackBuffer) {
        wl_buffer_destroy(m_fallbackBuffer);
        m_fallbackBuffer = nullptr;
    }
}

void WaylandWindow::setFallbackBuffer(wl_buffer* buffer) {
    if (m_fallbackBuffer) {
        wl_buffer_destroy(m_fallbackBuffer);
    }
    m_fallbackBuffer = buffer;
}

void WaylandWindow::setJoystickButtonCallback(
    VeraJoystickButtonCallback callback) {
    m_joyButtonCallback = callback;
    setJoystickButtonCallbackWayland(
        [this](uint32_t id, uint32_t btn, bool pressed) {
            if (m_joyButtonCallback) m_joyButtonCallback(id, btn, pressed);
        });
}

void WaylandWindow::setJoystickAxisCallback(VeraJoystickAxisCallback callback) {
    m_joyAxisCallback = callback;
    setJoystickAxisCallbackWayland(
        [this](uint32_t id, uint32_t axis, float val) {
            if (m_joyAxisCallback) m_joyAxisCallback(id, axis, val);
        });
}

void WaylandWindow::setDestructionCallback(
    nostd::Function<void(VeraWindow*)> callback) {
    (void)callback;
}

// Map platform-specific enum entries to sequential linux joydev button numbers
static constexpr uint8_t mapToLinuxJoydevButton(VeraJoystickButton button) {
    switch (button) {
        // Face Buttons
        case VeraJoystickButton::Cross:
        case VeraJoystickButton::XboxA:
            return 0;
        case VeraJoystickButton::Circle:
        case VeraJoystickButton::XboxB:
            return 1;
        case VeraJoystickButton::Square:
        case VeraJoystickButton::XboxX:
            return 2;
        case VeraJoystickButton::Triangle:
        case VeraJoystickButton::XboxY:
            return 3;

        // Bumpers
        case VeraJoystickButton::L1:
        case VeraJoystickButton::XboxLB:
            return 4;
        case VeraJoystickButton::R1:
        case VeraJoystickButton::XboxRB:
            return 5;

        // Triggers (Digital/Click Emulation)
        case VeraJoystickButton::L2:
        case VeraJoystickButton::XboxLT:
            return 6;
        case VeraJoystickButton::R2:
        case VeraJoystickButton::XboxRT:
            return 7;

        // Menu / System Options
        case VeraJoystickButton::Share:
        case VeraJoystickButton::XboxBack:
            return 8;
        case VeraJoystickButton::Options:
        case VeraJoystickButton::XboxStart:
            return 9;
        case VeraJoystickButton::PS:
        case VeraJoystickButton::XboxGuide:
            return 10;

        // Stick Clicks
        case VeraJoystickButton::L3:
        case VeraJoystickButton::XboxLS:
            return 11;
        case VeraJoystickButton::R3:
        case VeraJoystickButton::XboxRS:
            return 12;

        // Directional D-Pad Fallbacks
        case VeraJoystickButton::DpadUp:
            return 13;
        case VeraJoystickButton::DpadDown:
            return 14;
        case VeraJoystickButton::DpadLeft:
            return 15;
        case VeraJoystickButton::DpadRight:
            return 16;

        // Platform Exclusives
        case VeraJoystickButton::Touchpad:
            return 17;
        case VeraJoystickButton::XboxShare:
            return 18;

        default:
            return 255;
    }
}

bool WaylandWindow::isPressed(const VeraPressable& input) const {
    if (!m_state.isFocused) {
        return false;
    }

    switch (input.index()) {
        case 0: {  // VeraKey
            const auto& key = std::get<VeraKey>(input);
            if (key == VeraKey::Unknown || key == VeraKey::Count) return false;
            size_t keyIndex = static_cast<size_t>(key);
            return keyIndex < std::size(m_ctx.keyStates) &&
                   m_ctx.keyStates[keyIndex];
        }

        case 1: {  // VeraMouseButton
            const auto& mb = std::get<VeraMouseButton>(input);
            if (mb == VeraMouseButton::Count) return false;
            size_t mouseIndex = static_cast<size_t>(mb);
            return mouseIndex < std::size(m_ctx.mouseButtonStates) &&
                   m_ctx.mouseButtonStates[mouseIndex];
        }

        case 2: {  // VeraJoystickButton
            const auto& jb = std::get<VeraJoystickButton>(input);
            if (jb == VeraJoystickButton::Count) return false;

            uint8_t rawButtonId = mapToLinuxJoydevButton(jb);
            if (rawButtonId == 255) return false;

            const auto& joyState = getStateJoystickWayland(m_ctx, 0);
            return joyState.connected &&
                   rawButtonId < joyState.buttons.size() &&
                   joyState.buttons[rawButtonId];
        }

        default:
            return false;
    }
}
